"""updated check field to check_id on Order table

Revision ID: 05c7996fbb66
Revises: 14e7d6fa4327
Create Date: 2024-05-01 23:54:28.112511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05c7996fbb66'
down_revision: Union[str, None] = '14e7d6fa4327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('check_id', sa.Integer(), nullable=True))
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'checks', ['check_id'], ['id'], ondelete='SET NULL')
    op.drop_column('orders', 'check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('check', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ibfk_1', 'orders', 'checks', ['check'], ['id'], ondelete='SET NULL')
    op.drop_column('orders', 'check_id')
    # ### end Alembic commands ###
