"""added stock to Product model

Revision ID: 0f9a597aaf19
Revises: 3a4322562417
Create Date: 2024-03-14 13:47:17.998955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9a597aaf19'
down_revision: Union[str, None] = '3a4322562417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
