"""add password field to client table

Revision ID: 29e8900b1de8
Revises: 8e0ec7508fdb
Create Date: 2024-04-13 04:00:45.837027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e8900b1de8'
down_revision: Union[str, None] = '8e0ec7508fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password', sa.String(255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'password')
    # ### end Alembic commands ###
