"""updated field status from Order to Integer to match Status class that is a Enum

Revision ID: 46fcdeb3d0b1
Revises: 9833e991ad50
Create Date: 2024-04-23 02:43:41.570062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46fcdeb3d0b1'
down_revision: Union[str, None] = '9833e991ad50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###
