"""update cascade on category and products relationship

Revision ID: 48ab38b112e4
Revises: a54b2100464f
Create Date: 2024-03-31 16:51:43.939014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ab38b112e4'
down_revision: Union[str, None] = 'a54b2100464f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_ibfk_1', 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
