"""update set null on category and products relationship

Revision ID: 8e0ec7508fdb
Revises: 48ab38b112e4
Create Date: 2024-03-31 17:03:06.394992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e0ec7508fdb'
down_revision: Union[str, None] = '48ab38b112e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_ibfk_1', 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
