"""models

Revision ID: a54b2100464f
Revises: 
Create Date: 2024-03-15 13:31:42.015866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54b2100464f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('clients',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('number', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orders',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('date_time', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('status', sa.String(length=40), nullable=False),
                    sa.Column('mesa', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('products',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('stock', sa.Integer(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order_items',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('id_order', sa.Integer(), nullable=False),
                    sa.Column('id_product', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
                    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('clients')
    op.drop_table('categories')
    # ### end Alembic commands ###
