"""created field client_id on OrderItem to work properly, updated names of columns on OrderItem too

Revision ID: c40df5fd3add
Revises: 46fcdeb3d0b1
Create Date: 2024-04-23 20:57:37.424437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c40df5fd3add'
down_revision: Union[str, None] = '46fcdeb3d0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('order_items', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('order_items', sa.Column('client_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_ibfk_1', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.drop_column('order_items', 'id_order')
    op.drop_column('order_items', 'id_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('id_product', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('id_order', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_ibfk_1', 'order_items', 'orders', ['id_order'], ['id'])
    op.create_foreign_key('order_items_ibfk_2', 'order_items', 'products', ['id_product'], ['id'])
    op.drop_column('order_items', 'client_id')
    op.drop_column('order_items', 'product_id')
    op.drop_column('order_items', 'order_id')
    # ### end Alembic commands ###
