"""changed model Client and created model User

Revision ID: d56cd480b0c5
Revises: 29e8900b1de8
Create Date: 2024-04-13 17:18:52.604525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd56cd480b0c5'
down_revision: Union[str, None] = '29e8900b1de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('cpf', sa.String(length=11), nullable=False))
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('clients', sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('clients', 'cpf')
    op.drop_table('users')
    # ### end Alembic commands ###
