"""updated models OrderItem, Order and Product

Revision ID: f73d3e02ecd1
Revises: 0f9a597aaf19
Create Date: 2024-03-14 16:54:46.228119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f73d3e02ecd1'
down_revision: Union[str, None] = '0f9a597aaf19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'unittprice')
    op.drop_column('order_items', 'total')
    op.add_column('orders', sa.Column('mesa', sa.Integer(), nullable=True))
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_column('orders', 'order_items')
    op.drop_column('orders', 'total')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total', mysql.FLOAT(), nullable=True))
    op.add_column('orders', sa.Column('order_items', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_ibfk_1', 'orders', 'products', ['order_items'], ['id'])
    op.drop_column('orders', 'mesa')
    op.add_column('order_items', sa.Column('total', mysql.FLOAT(), nullable=True))
    op.add_column('order_items', sa.Column('unittprice', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
