networks:
  my-app-network:


services:
  bear:
    networks:
      - my-app-network
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy
      mysql-test:
        condition: service_healthy

  mysql:
    networks:
      - my-app-network
    container_name: mysql_db
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h "localhost" -u "${MYSQL_USER}" -p"${MYSQL_PASSWORD}"
      interval: 5s
      timeout: 5s
      retries: 55
      start_period: 5s

  mysql-test:
    networks:
      - my-app-network
    container_name: mysql_db_test
    image: mysql
    ports:
      - 3308:3306
    expose:
      - 3308
    env_file:
      - ./.env
    volumes:
      - mysql_data_test:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h "localhost" -u "${MYSQL_USER}" -p"${MYSQL_PASSWORD}"
      interval: 5s
      timeout: 5s
      retries: 55
      start_period: 5s

volumes:
  mysql_data:
  mysql_data_test:


