services:
  bear:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    env_file:
      - ./.env
    depends_on:
      - mysql

  mysql:
    container_name: mysql_db
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
